# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuu < Formula
  desc "Remove blank lines from the beginning and end of the file. Also, make duplicate blank lines into one."
  homepage "https://github.com/winebarrel/kuu"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.0/kuu_0.2.0_darwin_amd64.tar.gz"
      sha256 "fed563d7ab01994396e481c8de7005ca128d6e4a7e5730935dcb7002bde4be10"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.0/kuu_0.2.0_darwin_arm64.tar.gz"
      sha256 "1dcf07d133aa5480b5e254eb60ccc275a5f5844457169da12b7c6abfb91beb3f"

      def install
        bin.install 'kuu'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.0/kuu_0.2.0_linux_amd64.tar.gz"
      sha256 "3e9a743620c7354244dceadc78196270dfebd56f7086f45f0c6fa425b6f891be"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.0/kuu_0.2.0_linux_arm64.tar.gz"
      sha256 "66fcff172399739492793d0c1c010c3650e69cffca7b816973510fb6b1590f9e"

      def install
        bin.install 'kuu'
      end
    end
  end
end
