# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuu < Formula
  desc "Remove blank lines from the beginning and end of the file. Also, make duplicate blank lines into one."
  homepage "https://github.com/winebarrel/kuu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.1.0/kuu_0.1.0_darwin_amd64.tar.gz"
      sha256 "6bff20e1d6cfcbc98170fd9565eae015ee8214ba1234d004d2f7448ebadd411d"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/kuu/releases/download/v0.1.0/kuu_0.1.0_darwin_arm64.tar.gz"
      sha256 "6ef14baf6bb3fdae9b3f5e112f85bc335818ebde20986028d764d3b82daff356"

      def install
        bin.install 'kuu'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.1.0/kuu_0.1.0_linux_amd64.tar.gz"
      sha256 "23c1860c69b8161d7b4a397c3bd1ad80e9e96fd4f9abddb12def19bfcd6da1c1"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/kuu/releases/download/v0.1.0/kuu_0.1.0_linux_arm64.tar.gz"
      sha256 "69d8d8b784aef30fa3a8ea86d0f8723300ba6e045847211f9f7cb2917f8a7a21"

      def install
        bin.install 'kuu'
      end
    end
  end
end
