# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuu < Formula
  desc "Remove blank lines from the beginning and end of the file. Also, make duplicate blank lines into one."
  homepage "https://github.com/winebarrel/kuu"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.1/kuu_0.2.1_darwin_amd64.tar.gz"
      sha256 "30bb77fdf621cc416a293858b73a9a7191bc65613f9025184c4b4dbcbda3b4db"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.1/kuu_0.2.1_darwin_arm64.tar.gz"
      sha256 "ee297896010cc0ef1c04c4c03ee6d68aacdc02287b892f15e037474d19436c78"

      def install
        bin.install 'kuu'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.1/kuu_0.2.1_linux_amd64.tar.gz"
      sha256 "681c9d857a5726e0996195cc8dccd26b49deffe9291be2bf8ddfa2703918069a"

      def install
        bin.install 'kuu'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/kuu/releases/download/v0.2.1/kuu_0.2.1_linux_arm64.tar.gz"
      sha256 "3a71e5231a41f37dc6ef81131a7a8b7aad29dba88b28a9eec5b2af94adc41047"

      def install
        bin.install 'kuu'
      end
    end
  end
end
